name: mason_ma_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/project1.jpg
    - assets/images/project2.jpg
    - assets/images/project3.jpg
    - assets/images/project4.jpg
    - assets/images/project5.jpg
